[2022-10-08T12:12:45.206+0000] {processor.py:156} INFO - Started process (PID=178) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:12:45.207+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:12:45.207+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:12:45.207+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:12:45.210+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:12:45.209+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:12:45.210+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:12:45.226+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:14:11.498+0000] {processor.py:156} INFO - Started process (PID=178) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:14:11.499+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:14:11.500+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:14:11.499+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:14:11.501+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:14:11.501+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:14:11.502+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:14:11.517+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.021 seconds
[2022-10-08T12:14:41.612+0000] {processor.py:156} INFO - Started process (PID=211) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:14:41.613+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:14:41.614+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:14:41.613+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:14:41.615+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:14:41.615+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:14:41.616+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:14:41.632+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.021 seconds
[2022-10-08T12:15:11.729+0000] {processor.py:156} INFO - Started process (PID=243) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:15:11.729+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:15:11.730+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:15:11.730+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:15:11.732+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:15:11.731+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:15:11.732+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:15:11.748+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.022 seconds
[2022-10-08T12:15:41.845+0000] {processor.py:156} INFO - Started process (PID=266) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:15:41.846+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:15:41.846+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:15:41.846+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:15:41.848+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:15:41.847+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:15:41.848+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:15:41.866+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2022-10-08T12:16:11.961+0000] {processor.py:156} INFO - Started process (PID=298) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:16:11.962+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:16:11.962+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:16:11.962+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:16:11.964+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:16:11.963+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 3, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2022-10-08T12:16:11.964+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:16:11.980+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.021 seconds
[2022-10-08T12:16:36.057+0000] {processor.py:156} INFO - Started process (PID=321) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:16:36.058+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:16:36.058+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:16:36.058+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:16:36.931+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:16:36.931+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:16:36.932+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:16:36.946+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.891 seconds
[2022-10-08T12:17:07.084+0000] {processor.py:156} INFO - Started process (PID=354) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:17:07.084+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:17:07.085+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:17:07.085+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:17:07.400+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:17:07.399+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:17:07.400+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:17:07.414+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.333 seconds
[2022-10-08T12:17:37.529+0000] {processor.py:156} INFO - Started process (PID=387) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:17:37.529+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:17:37.530+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:17:37.530+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:17:37.845+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:17:37.844+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:17:37.845+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:17:37.860+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.333 seconds
[2022-10-08T12:18:07.975+0000] {processor.py:156} INFO - Started process (PID=420) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:18:07.976+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:18:07.977+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:18:07.977+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:18:08.296+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:18:08.295+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:18:08.296+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:18:08.312+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.339 seconds
[2022-10-08T12:18:38.427+0000] {processor.py:156} INFO - Started process (PID=444) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:18:38.428+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:18:38.429+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:18:38.429+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:18:38.740+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:18:38.739+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:18:38.740+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:18:38.755+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.330 seconds
[2022-10-08T12:19:08.870+0000] {processor.py:156} INFO - Started process (PID=477) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:19:08.871+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:19:08.871+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:19:08.871+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:19:09.183+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:19:09.182+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:19:09.183+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:19:09.198+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.331 seconds
[2022-10-08T12:19:39.314+0000] {processor.py:156} INFO - Started process (PID=510) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:19:39.315+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:19:39.316+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:19:39.315+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:19:39.550+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:19:39.549+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:19:39.550+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:19:39.567+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.255 seconds
[2022-10-08T12:20:09.676+0000] {processor.py:156} INFO - Started process (PID=543) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:20:09.677+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:20:09.678+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:20:09.678+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:20:09.938+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:20:09.937+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:20:09.938+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:20:09.955+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.281 seconds
[2022-10-08T12:20:40.070+0000] {processor.py:156} INFO - Started process (PID=567) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:20:40.071+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:20:40.071+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:20:40.071+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:20:40.297+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:20:40.296+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:20:40.297+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:20:40.313+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.246 seconds
[2022-10-08T12:21:10.423+0000] {processor.py:156} INFO - Started process (PID=600) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:21:10.424+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:21:10.424+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:21:10.424+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:21:10.652+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:21:10.651+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:21:10.653+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:21:10.669+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.248 seconds
[2022-10-08T12:21:40.780+0000] {processor.py:156} INFO - Started process (PID=633) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:21:40.781+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:21:40.782+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:21:40.781+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:21:41.015+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:21:41.013+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:21:41.015+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:21:41.031+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.254 seconds
[2022-10-08T12:22:11.144+0000] {processor.py:156} INFO - Started process (PID=664) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:22:11.145+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:22:11.145+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:22:11.145+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:22:11.373+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:22:11.372+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:22:11.374+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:22:11.389+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.248 seconds
[2022-10-08T12:22:41.504+0000] {processor.py:156} INFO - Started process (PID=690) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:22:41.505+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:22:41.505+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:22:41.505+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:22:41.737+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:22:41.736+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:22:41.737+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:22:41.753+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.253 seconds
[2022-10-08T12:23:11.868+0000] {processor.py:156} INFO - Started process (PID=723) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:23:11.868+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:23:11.869+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:23:11.869+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:23:12.099+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:23:12.098+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:23:12.099+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:23:12.115+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.250 seconds
[2022-10-08T12:23:42.229+0000] {processor.py:156} INFO - Started process (PID=756) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:23:42.230+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:23:42.231+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:23:42.231+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:23:42.462+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:23:42.461+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:23:42.462+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:23:42.479+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.252 seconds
[2022-10-08T12:24:12.591+0000] {processor.py:156} INFO - Started process (PID=786) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:24:12.592+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:24:12.592+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:24:12.592+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:24:12.829+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:24:12.828+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:24:12.830+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:24:12.847+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.258 seconds
[2022-10-08T12:24:42.964+0000] {processor.py:156} INFO - Started process (PID=813) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:24:42.965+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:24:42.966+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:24:42.966+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:24:43.201+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:24:43.200+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:24:43.201+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:24:43.218+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.257 seconds
[2022-10-08T12:25:13.331+0000] {processor.py:156} INFO - Started process (PID=846) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:25:13.332+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:25:13.332+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:25:13.332+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:25:13.559+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:25:13.558+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:25:13.559+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:25:13.575+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.247 seconds
[2022-10-08T12:25:43.689+0000] {processor.py:156} INFO - Started process (PID=879) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:25:43.690+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:25:43.690+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:25:43.690+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:25:43.924+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:25:43.923+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:25:43.924+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:25:43.941+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.255 seconds
[2022-10-08T12:26:14.053+0000] {processor.py:156} INFO - Started process (PID=903) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:26:14.054+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:26:14.054+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:26:14.054+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:26:14.281+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:26:14.279+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:26:14.281+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:26:14.297+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.247 seconds
[2022-10-08T12:26:44.411+0000] {processor.py:156} INFO - Started process (PID=936) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:26:44.412+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:26:44.412+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:26:44.412+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:26:44.635+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:26:44.634+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:26:44.635+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:26:44.651+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.243 seconds
[2022-10-08T12:27:14.760+0000] {processor.py:156} INFO - Started process (PID=969) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:27:14.761+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:27:14.761+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:27:14.761+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:27:14.992+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:27:14.991+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:27:14.992+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:27:15.009+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.252 seconds
[2022-10-08T12:27:45.120+0000] {processor.py:156} INFO - Started process (PID=1002) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:27:45.121+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:27:45.121+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:27:45.121+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:27:45.345+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:27:45.344+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:27:45.346+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:27:45.362+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.245 seconds
[2022-10-08T12:28:15.473+0000] {processor.py:156} INFO - Started process (PID=1026) to work on /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:28:15.474+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2022-10-08T12:28:15.474+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:28:15.474+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:28:15.702+0000] {logging_mixin.py:117} INFO - [2022-10-08T12:28:15.700+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 8, in <module>
    from kafka import KafkaConsumer, KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2022-10-08T12:28:15.702+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2022-10-08T12:28:15.719+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.248 seconds
